name: Build and publish
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/latest'
jobs:
  check-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set variables
        run: |
          echo "VERSION=`cat .github/latest`" >> $GITHUB_ENV
          echo "ARCH=x86_64-unknown-linux-musl" >> $GITHUB_ENV
      - name: Download upstream code
        run: curl -sL https://api.github.com/repos/geph-official/geph4/tarball/refs/tags/${{ env.VERSION }} | tar xvz
      - name: Patch upstream code
        run: |
          echo "GEPH=`ls | grep geph-official-geph4-`" >> $GITHUB_ENV
          echo ${{ env.GEPH }}
          ls ${{ env.GEPH }}
          git apply --directory=${{ env.GEPH }} .github/cross.patch
      - name: Download rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ env.ARCH }}
          override: true
      - name: Cross compile
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: '--release --locked --target ${{ env.ARCH }} --manifest-path=${{ env.GEPH }}/Cargo.toml'
        env:
          CC: clang
      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.VERSION }}
          path: target/x86_64-unknown-linux-musl/release/geph4-client
