name: Build and publish
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/latest'
jobs:
  build-aarch64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set variables
        run: echo "VERSION=`cat .github/latest`" >> $GITHUB_ENV
      - name: Download upstream code
        run: curl -sL https://api.github.com/repos/geph-official/geph4/tarball/refs/tags/${{ env.VERSION }} | tar xvz
      - name: Get source folder
        run: echo "GEPH=`ls | grep geph-official-geph4-`" >> $GITHUB_ENV
      - name: Cross compile
        uses: docker://messense/rust-musl-cross:aarch64-musl
        with:
          args: 'cargo build --release --locked --manifest-path=/github/workspace/${{ env.GEPH }}/Cargo.toml'
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: geph4-client-aarch64
          path: ${{ env.GEPH }}/target/aarch64-unknown-linux-musl/release/geph4-client
  build-x86_64:
    runs-on: ubuntu-latest
    if: always()
    needs: [ build-aarch64 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set variables
        run: echo "VERSION=`cat .github/latest`" >> $GITHUB_ENV
      - name: Download upstream code
        run: curl -sL https://api.github.com/repos/geph-official/geph4/tarball/refs/tags/${{ env.VERSION }} | tar xvz
      - name: Get source folder
        run: echo "GEPH=`ls | grep geph-official-geph4-`" >> $GITHUB_ENV
      - name: Cross compile
        uses: docker://messense/rust-musl-cross:x86_64-musl
        with:
          args: 'cargo build --release --locked --manifest-path=/github/workspace/${{ env.GEPH }}/Cargo.toml'
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: geph4-client-x86_64
          path: ${{ env.GEPH }}/target/x86_64-unknown-linux-musl/release/geph4-client
  release:
    runs-on: ubuntu-latest
    if: always()
    needs: [ build-x86_64 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set variables
        run: echo "VERSION=`cat .github/latest`" >> $GITHUB_ENV
      - name: Download artifact
        uses: actions/download-artifact@v2
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "geph4-client-*/geph4-client"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.VERSION }}
          commit: main
