name: Check new upstream release
on:
  workflow_dispatch:
  schedule:
    # Check every hour
    - cron:  '0 * * * *'
jobs:
  check-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PUSH_TOKEN }}
      - name: Fetch release version
        run: |
          curl -sL https://api.github.com/repos/geph-official/geph4/tags | \
          jq -r ".[0].name" > latest
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'docker-geph'
          git config --global user.email '92070461+docker-geph@users.noreply.github.com'
          git commit -am "`cat latest`"
          git push
